apiVersion: v1
name: stolon
version: 1.7.0
appVersion: 0.16.0
description: Stolon - PostgreSQL cloud native High Availability.
home: https://github.com/sorintlab/stolon
icon: https://i.imgur.com/tIW8sAW.png
sources:
  - https://github.com/sorintlab/stolon
  - https://github.com/iomedhealth/helm_stolon
deprecated: false
engine: gotpl
